# Generated by Django 3.2 on 2023-01-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='user_avatar', verbose_name='User photo'),
        ),
    ]
