# Generated by Django 3.2 on 2023-01-14 19:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='user_avatar/default.png', upload_to=users.models.get_upload_path, verbose_name='User photo'),
        ),
    ]
