# Generated by Django 3.2 on 2023-01-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures_product/%Y/%m/%d/'),
        ),
    ]
