# Generated by Django 3.2.4 on 2023-01-15 18:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_categoryproduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, max_length=150, null=True, populate_from=('category', 'name'), unique=True),
        ),
    ]
