# Generated by Django 3.2.4 on 2023-01-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productattribute_valueproductattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valueproductattribute',
            options={'ordering': ['id'], 'verbose_name': 'Value Product Attribute', 'verbose_name_plural': 'Values Products Attributes'},
        ),
    ]
