# Generated by Django 3.2.4 on 2023-01-29 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_valueproductattribute_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueBladesAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_attribute', models.CharField(blank=True, max_length=40, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Value Product Attribute',
                'verbose_name_plural': 'Values Products Attributes',
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='ProductAttribute',
            new_name='BladesProductAttribute',
        ),
        migrations.DeleteModel(
            name='ValueProductAttribute',
        ),
        migrations.AddField(
            model_name='valuebladesattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bladesproductattribute'),
        ),
        migrations.AddField(
            model_name='valuebladesattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_product_attribute', to='store.product'),
        ),
    ]
