# Generated by Django 3.2.4 on 2023-01-29 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230129_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bladesproductattribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blades_attribute', to='store.categoryproduct', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='valuebladesattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bladesproductattribute'),
        ),
        migrations.AlterField(
            model_name='valuebladesattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_blades_attribute', to='store.product'),
        ),
    ]
