# Generated by Django 3.2.4 on 2023-01-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20230129_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bladesproductattribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categoryproduct', verbose_name='Category'),
        ),
    ]
