# Generated by Django 3.2.4 on 2023-01-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_bladesproductattribute_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuebladesattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
