# Generated by Django 3.2.4 on 2023-01-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_valuebladesattribute_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='BladesBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BladesComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BladesHandleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BladesSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BladesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='valuebladesattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='valuebladesattribute',
            name='value_attribute',
        ),
        migrations.AddField(
            model_name='valuebladesattribute',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.bladesbrand'),
        ),
        migrations.AddField(
            model_name='valuebladesattribute',
            name='composition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.bladescomposition'),
        ),
        migrations.AddField(
            model_name='valuebladesattribute',
            name='handle_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.bladeshandletype'),
        ),
        migrations.AddField(
            model_name='valuebladesattribute',
            name='size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.bladessize'),
        ),
        migrations.AddField(
            model_name='valuebladesattribute',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.bladestype'),
        ),
    ]
