# Generated by Django 3.2.4 on 2023-01-29 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20230129_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallsBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BallsPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BallsRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ValueBallsAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.ballsbrand')),
                ('package', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.ballspackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.ballsrank')),
            ],
            options={
                'verbose_name': 'Value Ball Attribute',
                'verbose_name_plural': 'Values Balls Attributes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BallsProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categoryproduct', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Ball Attribute',
                'verbose_name_plural': 'Balls Attributes',
                'ordering': ['id'],
            },
        ),
    ]
