# Generated by Django 3.2.4 on 2023-01-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_ballsbrand_ballspackage_ballsproductattribute_ballsrank_valueballsattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackpacksBagsBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BackpacksBagsColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BackpacksBagsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ValueBackpacksBagsAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.backpacksbagsbrand')),
                ('color', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.backpacksbagscolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.backpacksbagstype')),
            ],
            options={
                'verbose_name': 'Value Backpack and Bag Attribute',
                'verbose_name_plural': 'Values Backpacks and Bags Attributes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BackpacksBagsProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categoryproduct', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Backpack and Bag Attribute',
                'verbose_name_plural': 'Backpacks and Bags Attributes',
                'ordering': ['id'],
            },
        ),
    ]
