# Generated by Django 3.2.4 on 2023-01-30 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_backpacksbagsbrand_backpacksbagscolor_backpacksbagsproductattribute_backpacksbagstype_valuebackpacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetsBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NetsColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ValueNetsAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.netsbrand')),
                ('color', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.netscolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Value Net Attribute',
                'verbose_name_plural': 'Values Nets Attributes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NetsProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categoryproduct', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Net Attribute',
                'verbose_name_plural': 'Nets Attributes',
                'ordering': ['id'],
            },
        ),
    ]
