# Generated by Django 3.2.4 on 2023-01-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_netsbrand_netscolor_netsproductattribute_valuenetsattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablesBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TablesColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TablesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TablesThickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ValueTablesAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.tablesbrand')),
                ('color', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.tablescolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.tablessection')),
                ('thickness', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.tablesthickness')),
            ],
            options={
                'verbose_name': 'Value Table Attribute',
                'verbose_name_plural': 'Values Tables Attributes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TablesProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categoryproduct', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Table Attribute',
                'verbose_name_plural': 'Tables Attributes',
                'ordering': ['id'],
            },
        ),
    ]
