# Generated by Django 3.2.4 on 2023-01-30 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_tablesbrand_tablescolor_tablesproductattribute_tablessection_tablesthickness_valuetablesattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacketsAverageWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RacketsBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RacketsHandleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RacketsRubbersThickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RacketsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ValueRacketsAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_weight', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.racketsaverageweight')),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.racketsbrand')),
                ('handle_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.racketshandletype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('rubbers_thickness', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.racketsrubbersthickness')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.racketstype')),
            ],
            options={
                'verbose_name': 'Value Racket Attribute',
                'verbose_name_plural': 'Values Rackets Attributes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RacketsProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categoryproduct', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Racket Attribute',
                'verbose_name_plural': 'Rackets Attributes',
                'ordering': ['id'],
            },
        ),
    ]
