# Generated by Django 3.2.4 on 2023-01-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_racketsaverageweight_racketsbrand_racketshandletype_racketsproductattribute_racketsrubbersthickness_'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoriesColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AccessoriesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ValueAccessoriesAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.accessoriesbrand')),
                ('color', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.accessoriescolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.accessoriestype')),
            ],
            options={
                'verbose_name': 'Value Accessory Attribute',
                'verbose_name_plural': 'Values Accessories Attributes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AccessoriesProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categoryproduct', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Accessorie Attribute',
                'verbose_name_plural': 'Accessories Attributes',
                'ordering': ['id'],
            },
        ),
    ]
