# Generated by Django 3.2.4 on 2023-02-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_accessoriesbrand_accessoriescolor_accessoriesproductattribute_accessoriestype_valueaccessoriesattrib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.categoryproduct'),
        ),
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_product', to='store.product'),
        ),
        migrations.AlterField(
            model_name='valuebladesattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blade_attribute', to='store.product'),
        ),
    ]
