# Generated by Django 3.2.4 on 2023-02-03 17:12

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20230203_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=store.models.get_upload_path),
        ),
    ]
