# Generated by Django 3.2.4 on 2023-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20230204_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bestseller',
            field=models.BooleanField(default=True, verbose_name='Bestseller'),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True, verbose_name='New'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.BooleanField(default=True, verbose_name='Stock'),
        ),
    ]
