# Generated by Django 3.2.4 on 2023-02-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_ratingproduct_ratingstarproduct_reviewsproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_product', to='store.product', verbose_name='Product'),
        ),
    ]
