# Generated by Django 3.2.4 on 2023-02-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_ratingstarproduct_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsproduct',
            name='parent',
        ),
    ]
