# Generated by Django 3.2.4 on 2023-02-17 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0032_remove_reviewsproduct_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsproduct',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewsproduct',
            name='ip',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='reviewsproduct',
            name='rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reviewsproduct',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=8),
        ),
        migrations.AddField(
            model_name='reviewsproduct',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reviewsproduct',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
