# Generated by Django 3.2.4 on 2023-02-17 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20230217_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsproduct',
            name='rate',
        ),
    ]
