# Generated by Django 3.2.4 on 2023-02-20 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_remove_reviewsproduct_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valueaccessoriesattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_attribute', to='store.product'),
        ),
        migrations.AlterField(
            model_name='valuebackpacksbagsattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_attribute', to='store.product'),
        ),
        migrations.AlterField(
            model_name='valueballsattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ball_attribute', to='store.product'),
        ),
        migrations.AlterField(
            model_name='valuenetsattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_attribute', to='store.product'),
        ),
        migrations.AlterField(
            model_name='valueracketsattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racket_attribute', to='store.product'),
        ),
        migrations.AlterField(
            model_name='valuerubbersattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubber_attribute', to='store.product'),
        ),
        migrations.AlterField(
            model_name='valuetablesattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_attribute', to='store.product'),
        ),
    ]
