# Generated by Django 3.2.4 on 2023-02-20 22:46

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20230220_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to=store.models.get_upload_path_category),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='visibility_catalog_cards',
            field=models.BooleanField(default=True, verbose_name='Visibility in catalog cards'),
        ),
    ]
